var annotated_dup =
[
    [ "CADMesh", "namespace_c_a_d_mesh.html", [
      [ "File", "namespace_c_a_d_mesh_1_1_file.html", [
        [ "Reader", "class_c_a_d_mesh_1_1_file_1_1_reader.html", "class_c_a_d_mesh_1_1_file_1_1_reader" ],
        [ "Token", "struct_c_a_d_mesh_1_1_file_1_1_token.html", "struct_c_a_d_mesh_1_1_file_1_1_token" ],
        [ "Item", "struct_c_a_d_mesh_1_1_file_1_1_item.html", "struct_c_a_d_mesh_1_1_file_1_1_item" ],
        [ "State", "struct_c_a_d_mesh_1_1_file_1_1_state.html", "struct_c_a_d_mesh_1_1_file_1_1_state" ],
        [ "__FinalState", "struct_c_a_d_mesh_1_1_file_1_1_____final_state.html", "struct_c_a_d_mesh_1_1_file_1_1_____final_state" ],
        [ "Lexer", "class_c_a_d_mesh_1_1_file_1_1_lexer.html", "class_c_a_d_mesh_1_1_file_1_1_lexer" ],
        [ "BuiltInReader", "class_c_a_d_mesh_1_1_file_1_1_built_in_reader.html", "class_c_a_d_mesh_1_1_file_1_1_built_in_reader" ],
        [ "STLReader", "class_c_a_d_mesh_1_1_file_1_1_s_t_l_reader.html", "class_c_a_d_mesh_1_1_file_1_1_s_t_l_reader" ],
        [ "OBJReader", "class_c_a_d_mesh_1_1_file_1_1_o_b_j_reader.html", "class_c_a_d_mesh_1_1_file_1_1_o_b_j_reader" ],
        [ "PLYReader", "class_c_a_d_mesh_1_1_file_1_1_p_l_y_reader.html", "class_c_a_d_mesh_1_1_file_1_1_p_l_y_reader" ]
      ] ],
      [ "Mesh", "class_c_a_d_mesh_1_1_mesh.html", "class_c_a_d_mesh_1_1_mesh" ],
      [ "CADMeshTemplate", "class_c_a_d_mesh_1_1_c_a_d_mesh_template.html", "class_c_a_d_mesh_1_1_c_a_d_mesh_template" ],
      [ "TessellatedMesh", "class_c_a_d_mesh_1_1_tessellated_mesh.html", "class_c_a_d_mesh_1_1_tessellated_mesh" ]
    ] ],
    [ "abcDataFile", "classabc_data_file.html", "classabc_data_file" ],
    [ "abcDetectorComponent", "classabc_detector_component.html", "classabc_detector_component" ],
    [ "abcMaterialData", "classabc_material_data.html", "classabc_material_data" ],
    [ "AngularScan", "class_angular_scan.html", "class_angular_scan" ],
    [ "arg_date", "structarg__date.html", "structarg__date" ],
    [ "arg_dbl", "structarg__dbl.html", "structarg__dbl" ],
    [ "arg_end", "structarg__end.html", "structarg__end" ],
    [ "arg_file", "structarg__file.html", "structarg__file" ],
    [ "arg_hdr", "structarg__hdr.html", "structarg__hdr" ],
    [ "arg_int", "structarg__int.html", "structarg__int" ],
    [ "arg_lit", "structarg__lit.html", "structarg__lit" ],
    [ "arg_rem", "structarg__rem.html", "structarg__rem" ],
    [ "arg_rex", "structarg__rex.html", "structarg__rex" ],
    [ "arg_str", "structarg__str.html", "structarg__str" ],
    [ "DEGG", "class_d_e_g_g.html", "class_d_e_g_g" ],
    [ "DEggHarness", "class_d_egg_harness.html", "class_d_egg_harness" ],
    [ "GlobalPosition", "struct_global_position.html", "struct_global_position" ],
    [ "IceCubeIce", "class_ice_cube_ice.html", "class_ice_cube_ice" ],
    [ "InputDataManager", "class_input_data_manager.html", "class_input_data_manager" ],
    [ "LOM16", "class_l_o_m16.html", "class_l_o_m16" ],
    [ "LOM18", "class_l_o_m18.html", "class_l_o_m18" ],
    [ "mDOM", "classm_d_o_m.html", "classm_d_o_m" ],
    [ "mDOMFlasher", "classm_d_o_m_flasher.html", "classm_d_o_m_flasher" ],
    [ "mDOMHarness", "classm_d_o_m_harness.html", "classm_d_o_m_harness" ],
    [ "NoOptics", "class_no_optics.html", "class_no_optics" ],
    [ "OMSimAnalysisManager", "class_o_m_sim_analysis_manager.html", "class_o_m_sim_analysis_manager" ],
    [ "OMSimCommandArgsTable", "class_o_m_sim_command_args_table.html", "class_o_m_sim_command_args_table" ],
    [ "OMSimDetectorConstruction", "class_o_m_sim_detector_construction.html", "class_o_m_sim_detector_construction" ],
    [ "OMSimEventAction", "class_o_m_sim_event_action.html", "class_o_m_sim_event_action" ],
    [ "OMSimPhysicsList", "class_o_m_sim_physics_list.html", "class_o_m_sim_physics_list" ],
    [ "OMSimPMTConstruction", "class_o_m_sim_p_m_t_construction.html", "class_o_m_sim_p_m_t_construction" ],
    [ "OMSimPMTResponse", "class_o_m_sim_p_m_t_response.html", "class_o_m_sim_p_m_t_response" ],
    [ "OMSimPrimaryGeneratorAction", "class_o_m_sim_primary_generator_action.html", "class_o_m_sim_primary_generator_action" ],
    [ "OMSimRunAction", "class_o_m_sim_run_action.html", "class_o_m_sim_run_action" ],
    [ "OMSimSteppingAction", "class_o_m_sim_stepping_action.html", "class_o_m_sim_stepping_action" ],
    [ "OMSimTrackingAction", "class_o_m_sim_tracking_action.html", "class_o_m_sim_tracking_action" ],
    [ "OMSimUIinterface", "class_o_m_sim_u_iinterface.html", "class_o_m_sim_u_iinterface" ],
    [ "ParameterTable", "class_parameter_table.html", "class_parameter_table" ],
    [ "pDOM", "classp_d_o_m.html", "classp_d_o_m" ],
    [ "ReflectiveSurface", "class_reflective_surface.html", "class_reflective_surface" ],
    [ "RefractionAndAbsorption", "class_refraction_and_absorption.html", "class_refraction_and_absorption" ],
    [ "RefractionOnly", "class_refraction_only.html", "class_refraction_only" ]
];